### ISSUE TITLE
链接不能下载

### ISSUE THREAD

**Issue by zerowq** [rainx/php-mmseg#1]
这个地方的链接不能下载
找不到 php的扩展

**Comment by rainx** [comment]
好的，我和coreseek的同学问问，看看能不能恢复链接，或者找一个备用的下载链接

**Comment by rainx** [comment]
@zerowq 可以从这个备用链接下载 https://dl.dropboxusercontent.com/u/477485/coreseek/coreseek-3.2.14.tar.gz （需要翻墙）

**Comment by rainx** [comment]
@zerowq 链接不在了，已经将依赖放到git仓库里了
